# Generated by Django 4.1.7 on 2023-03-01 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("todos", "0002_todoitem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="todoitem",
            name="todo",
        ),
        migrations.AddField(
            model_name="todoitem",
            name="list",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="todos.todolist",
            ),
        ),
    ]
